src/main/java/ejb/SessionBean.java
/*
 * Atiar Khan, s0217325
 */
package ejb;

import entity.BookEntity;
import entity.CDEntity;
import entity.CustomerEntity;
import entity.OrderEntity;
import entity.ProductEntity;
import java.util.List;
import javax.ejb.Stateless;
import javax.ejb.LocalBean;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

@Stateless
@LocalBean
public class SessionBean {

    @PersistenceContext(unitName = "Assignment2-Snapshot")
    private EntityManager em;

    public List<CustomerEntity> getCustomers() {
        Query query = em.createNamedQuery("Customer.findAll");
        return query.getResultList();
    }

    public List<CustomerEntity> getCustomersByName(String name) {
        if (name == null || name.length() == 0 || name.equals("")) {
            return getCustomers();
        }
        Query query = em.createNamedQuery("Customer.findByCustomersName").setParameter("name", name);
        return query.getResultList();
    }
    public CustomerEntity getCustomerById(Long id) {
        Query query = em.createNamedQuery("Customer.findByCustomersId").setParameter("id", id);
        return (CustomerEntity) query.getResultList().get(0);
    }
    public List<BookEntity> getBooks() {
        Query query = em.createNamedQuery("Book.findAll");
        return query.getResultList();
    }
    public List<BookEntity> getBooksByISBN(String isbn) {
        if (isbn == null || isbn.length() == 0 || isbn.equals("")) {
            return getBooks();
        }
        Query query = em.createNamedQuery("Book.findByBooksISBN").setParameter("isbn", isbn);
        return query.getResultList();
    }
    public List<CDEntity> getCDs() {
        Query query = em.createNamedQuery("CD.findAll");
        return query.getResultList();
    }
    public List<CDEntity> getCDsByTitle(String title) {
        if (title == null || title.length() == 0 || title.equals("")) {
            return getCDs();
        }
        Query query = em.createNamedQuery("CD.findByCDsTitle").setParameter("title", title);
        return query.getResultList();
    }
    public List<OrderEntity> getOrders() {
        Query query = em.createNamedQuery("Order.findAll");
        return query.getResultList();
    }
    public List<OrderEntity> getOrdersById(Long id) {
        if (id == null || id==0) {
            return getOrders();
        }
        Query query = em.createNamedQuery("Order.findByOrdersId").setParameter("id", id);
        return query.getResultList();
    }
    public List<ProductEntity> getProducts() {
        Query query = em.createNamedQuery("Product.findAll");
        return query.getResultList();
    }
    public ProductEntity getProductById(Long id) {
        Query query = em.createNamedQuery("Product.findByProductsId").setParameter("id", id);
        return (ProductEntity) query.getResultList().get(0);
    }
    public void save(Object object) {
        em.persist(object);
    }

    public void update(Object object) {
        em.merge(object);
    }

    public void delete(Object object) {
        em.remove(em.merge(object));
    }
    
  }

src/main/webapp/book/Create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Create a new Book</title>
        <link type="text/css" rel="stylesheet" href="../style.css"/>
        
    </h:head>
    <h:body>
        <div class="header">
            <h1><h:outputText value="Create a new Book"/></h1>
            <br/>
            
        </div>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputLabel value="Title:" for="title" />
                <h:inputText id="title" value="#{book.book.title}" title="Title" />
                <h:outputLabel value="Author:" for="author" />
                <h:inputText id="author" value="#{book.book.author}" title="Author" />
                <h:outputLabel value="Price:" for="price" />
                <h:inputText id="price" value="#{book.book.price}" title="Price" />
                <h:outputLabel value="Description:" for="description" />
                <h:inputTextarea id="description" value="#{book.book.description}" title="Description" />
                <h:outputLabel value="ISBN:" for="isbn" />
                <h:inputText id="isbn" value="#{book.book.isbn}" title="ISBN" />
                <h:outputLabel value="Number of Books:" for="number" />
                <h:inputText id="number" value="#{book.book.count}" title="Number of Books" />
            </h:panelGrid>
            <h:commandLink action="#{book.create()}" value="Create Book" />
            <div class ="footer">
                <h:commandLink action="#{book.prepareList()}" value="The Stock of Books" />
                <h:commandLink action="#{book.mainPage()}" value="Main Page"/>
            </div>
<cr>COIT20227: Enterprise Computing. Student ID: s0217325</cr>
          
        </h:form>
    </h:body>
</html>

src/main/webapp/book/Found.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsf/core"
      >
    <h:head>
        <title>The Found Books</title>
        <link type="text/css" rel="stylesheet" href="../style.css"/>
    </h:head>
    <h:body>
        <div class="header">
            <h1><h:outputText value="The Found Books"/></h1>
            <br/>
             </div>
        <c:view>
            <h:form>
                <h:dataTable value="#{book.foundbooks}" var="item" styleClass="table"
                             headerClass="table-header"
                             rowClasses="table-odd-row,table-even-row">
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Isbn"/>
                        </c:facet>
                        <h:outputText value="#{item.isbn}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Title"/>
                        </c:facet>
                        <h:outputText value="#{item.title}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Author"/>
                        </c:facet>
                        <h:outputText value="#{item.author}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Price"/>
                        </c:facet>
                        <h:outputText value="#{item.price}"/>
                    </h:column>
                    <h:column class="description">
                        <c:facet name="header">
                            <h:outputText value="Description"/>
                        </c:facet>
                        <h:outputText value="#{item.description}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Count"/>
                        </c:facet>
                        <h:outputText value="#{item.count}"/>
                    </h:column>
                </h:dataTable>
                <p>Total: #{book.foundbooks.size()}</p>
                <div class="footer">
                    <h:commandLink action="#{book.prepareCreate}" value="Create a new Book"/>
                    <h:commandLink action="#{book.mainPage()}" value="Main Page"/>
                </div>
            <cr>COIT20227: Enterprise Computing. Student ID: s0217325</cr>
      
            </h:form>
        </c:view>
    </h:body>
</html>

src/main/webapp/book/List.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsf/core"
      >
    <h:head>
        <title>The Stock of Books</title>
        <link type="text/css" rel="stylesheet" href="../style.css"/>
    </h:head>
    <h:body>
        <div class="header">
            <h1><h:outputText value="The Stock of Books"/></h1>
            <br/>
             </div>
        <c:view>
            <h:form>
                <h:messages style="color:blue;margin:8px;" />
                <h:dataTable value="#{book.books}" var="item" styleClass="table"
                             headerClass="table-header"
                             rowClasses="table-odd-row,table-even-row">
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Isbn"/>
                        </c:facet>
                        <h:outputText value="#{item.isbn}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Title"/>
                        </c:facet>
                        <h:commandLink action="#{book.prepareView(item)}" value="#{item.title}"/>
                    </h:column>
                </h:dataTable>
                <p>Total: #{book.books.size()}</p>
                <div class="footer">
                    <h:commandLink action="#{book.prepareCreate}" value="Create a new Book"/>
                    <h:commandLink action="#{book.mainPage()}" value="Main Page"/>
                </div>
           
             <cr>COIT20227: Enterprise Computing. Student ID: s0217325</cr>
      
            </h:form>
        </c:view>
    </h:body>
</html>

src/main/webapp/book/Search.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Search for a Book</title>
        <link type="text/css" rel="stylesheet" href="../style.css"/>
    </h:head>
    <h:body>
        <div class="header">
            <h1><h:outputText value="Search for a Book"/></h1>
            <br/>
            </div>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputLabel value="ISBN:" for="isbn" />
                <h:inputText id="isbn" value="#{book.searchISBN}" title="ISBN" />
            </h:panelGrid>
            <h:commandLink action="#{book.prepareSearch()}" value="Search for a Book" />
            <div class="footer">
                <h:commandLink action="#{customer.prepareList()}" value="The Stock of Books" />
                <h:commandLink action="#{customer.mainPage()}" value="Main Page"/>
            </div>
             <cr>COIT20227: Enterprise Computing. Student ID: s0217325</cr>
      
        </h:form>
    </h:body>
</html>